name: simple_calculator
description: Just a simple calculator. Nothing more.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.0-424.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  stacked_themes: ^0.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/JetBrainsMonoNL-Bold.ttf
  assets:
    - assets/logo.png
