name: simple_calculator
description: Just a simple calculator. Nothing more.
publish_to: 'none'
version: 0.0.6+6

environment:
  sdk: '>=2.17.0-149.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  stacked_themes: ^0.3.10
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.1.0
  function_tree: ^0.8.13
  get_it: ^7.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rainbow.png
    - assets/fonts/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 800
